//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: cats_and_dogs.proto
// Note: requires additional types generated from: empty_msg.proto
namespace rpc
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttackRequest")]
  public partial class AttackRequest : global::ProtoBuf.IExtensible
  {
    public AttackRequest() {}
    
    private uint _strength = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttackResponse")]
  public partial class AttackResponse : global::ProtoBuf.IExtensible
  {
    public AttackResponse() {}
    
    private rpc.AttackResponse.AttackResult _result = rpc.AttackResponse.AttackResult.UNKNOWN;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(rpc.AttackResponse.AttackResult.UNKNOWN)]
    public rpc.AttackResponse.AttackResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"AttackResult")]
    public enum AttackResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN", Value=0)]
      UNKNOWN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HIT", Value=1)]
      HIT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MISS", Value=2)]
      MISS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WRONG_TURN", Value=3)]
      WRONG_TURN = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public interface ICatsAndDogs
    {
      rpc.EmptyMsg EnterMatch(rpc.EmptyMsg request);
    rpc.EmptyMsg Exit(rpc.EmptyMsg request);
    rpc.AttackResponse Attack(rpc.AttackRequest request);
    
    }
    
    
}